import { configureStore } from "@reduxjs/toolkit";
import templateSlice from "./templateSlice";
const store = configureStore({
  reducer: {
    tempalte: templateSlice.reducer,
  },
});

export default store;

// export the actions generated by the slice
export const templateActions = templateSlice.actions;
